package homework1.app;

/**
 * Возможные состояния пользователя
 */
public enum UserState {
    INITIAL_STATE,
    LOGIN_STATE,
    REGISTER_STATE,
    MAIN_MENU_STATE,
    DELETE_ACCOUNT_STATE,
    UPDATE_ACCOUNT_STATE,
    CREATE_HABIT_STATE,
    CHOOSING_HABIT_FILTER_STATE,
    WATCHING_HABIT_LIST_STATE,
    WATCHING_HABIT_STATE,
    UPDATE_HABIT_STATE,
    DELETE_HABIT_STATE,
    UPDATE_HABIT_NAME_STATE,
    CHOOSE_HABIT_STATISTICS_STATE,
    WATCHING_HABIT_RECORDS_STATE,
    WATCHING_HABIT_RECORD_STATE,
    UPDATE_HABIT_RECORD_STATE,
    DELETE_HABIT_RECORD_STATE,
    CHOOSING_STATISTICS_STATE,
    WATCHING_STATISTICS_STATE,
    WATCHING_USERS_STATE,
    WATCHING_USER_STATE,
    DELETE_USER_STATE,
    BLOCK_USER_STATE
}
